backstore/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register, name="register"),
    path(
        "login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"
    ),
    # path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("logout/", views.logout_view, name="logout"),
    # path("profile/", views.profile, name="profile"),
    path("update_profile/", views.update_profile, name="update_profile"),
    path("view_profile/", views.view_profile, name="view_profile"),
]

backstore/backstore/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("products/", include("products.urls")),
    path("accounts/", include("accounts.urls")),
    path("cart/", include("cart.urls")),
    path("orders/", include("orders.urls")),
]

backstore/cart/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from orders.views import order_create

app_name = "cart"

urlpatterns = [
    path("add/<int:product_id>/", views.add_to_cart, name="add_to_cart"),
    path("cart/", views.cart_detail, name="cart_detail"),
    path("clean_cart", views.clean_cart, name="clean_cart"),
    path("remove/<int:item_id>", views.remove_from_cart, name="remove_from_cart"),
    path("order_create", order_create, name="order_create"),
]

backstore/products/urls.py
from django.urls import path
from . import views
from cart.views import add_to_cart
from .views import Ping, ProductList

app_name = "products"

urlpatterns = [
    path("add/", views.add_product, name="add_product"),
    path("healthcheck/", views.health_check, name="health_check"),
    path("products/", views.products, name="products"),
    path("add_to_cart/<int:product_id>/", add_to_cart, name="add_to_cart"),
    path("api/products/", ProductList.as_view(), name="api_products"),
    path("api/ping/", Ping.as_view(), name="api_ping"),
]

backstore/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product
from orders.models import Order, OrderProduct


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    address = models.CharField(max_length=250, blank=True, null=True)

    def __str__(self):
        return self.user.username

    @property
    def get_cart_total(self):
        # Get the user's open order, if any
        open_order = self.get_open_order()
        if open_order:
            return open_order.get_order_total
        else:
            return 0

    @property
    def get_cart_items(self):
        # Get the user's open order, if any
        open_order = self.get_open_order()
        if open_order:
            return open_order.get_order_products
        else:
            return []

    def get_open_order(self):
        # Get the user's open order, or create one if none exists
        open_orders = Order.objects.filter(user=self.user, status="open")
        if open_orders.exists():
            return open_orders.first()
        else:
            new_order = Order.objects.create(user=self.user, status="open")
            return new_order

    def complete_order(self):
        # Complete the user's open order, if any
        open_order = self.get_open_order()
        if open_order:
            open_order.status = "complete"
            open_order.save()

backstore/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

from .models import Account


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    def clean_email(self):
        email = self.cleaned_data["email"]
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                "This email address is already in use. Please use a different email address."
            )
        return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
            Account.objects.create(user=user)
        return user


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email"]

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if (
            email
            and User.objects.filter(email=email).exclude(pk=self.instance.pk).exists()
        ):
            raise forms.ValidationError(
                _("This email address is already in use. Please use a different email.")
            )
        return email


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ["phone_number", "address"]

backstore/accounts/views.py
import logging
from django.contrib import messages
from utils.logging_config import configure_logger
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from .models import Account
from .forms import CustomUserCreationForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth import (
    update_session_auth_hash,
    logout,
    authenticate,
    login as auth_login,
)


app_name = "accounts"
log_file_path = f"{app_name}/{app_name}.out"
log_level = logging.DEBUG
logger = configure_logger(log_file_path, log_level)


def login(request):
    if request.method == "POST":
        # get the username and password from the form data
        username = request.POST.get("username")
        password = request.POST.get("password")

        # authenticate the user
        user = authenticate(request, username=username, password=password)

        # check if authentication was successful
        if user is not None:
            # log the user in and redirect to their profile page
            auth_login(request, user)
            return redirect("accounts:view_profile")
        else:
            # authentication failed, show an error message
            error_message = "Invalid username or password."
            return render(request, "login.html", {"error_message": error_message})
    else:
        # display the login form
        return render(request, "login.html")


@login_required
def view_profile(request):
    logger.info("view_profile() was called.")
    context = {
        "user": request.user,
    }
    logger.debug(f"{context=}")
    return render(request, "view_profile.html", context)

    # return render(request, "profile.html", {"user": request.user})


@login_required
def update_profile(request):
    logger.debug("update_profile() was called.")
    user = request.user
    logger.debug(f"{user=}")
    if request.method == "POST":
        user_form = UserUpdateForm(request.POST, instance=user)
        profile_form = ProfileUpdateForm(request.POST, instance=user.account)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Your profile has been updated!")
            return redirect("accounts:update_profile")
        else:
            messages.error(request, "Please correct the errors below.")
    else:
        user_form = UserUpdateForm(instance=user)
        if hasattr(user, "account"):
            profile_form = ProfileUpdateForm(instance=user.account)
        else:
            profile_form = ProfileUpdateForm()

    context = {"user_form": user_form, "profile_form": profile_form}
    return render(request, "update_profile.html", context)


def register(request):
    logger.info("register() was called.")
    if request.method == "POST":
        logger.debug(f"request method was POST. - {request.POST=} - {request.body=}")
        # form = UserCreationForm(request.POST)
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            logger.debug("form is valid")
            form.save()
            return redirect("accounts:view_profile")
        logger.error(f"Seems like form is not valid! - {form.errors=}")
    else:
        logger.debug(
            f"request method was NOT POST. - {request.POST=} - {request.body=}"
        )
        form = UserCreationForm()
    return render(request, "register.html", {"form": form})


@login_required
def orders(request):
    logger.info("orders() was called.")
    # TODO: add logic to display user's orders
    return render(request, "orders.html", {})


def logout_view(request):
    logout(request)
    return redirect("accounts:login")

backstore/accounts/templates/base.html
<ul>

    <li><a href="{% url 'products:products' %}">Products</a></li>
    {% if user.is_authenticated %}
      <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
      <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
    {% else %}
      <li><a href="{% url 'accounts:login' %}">Login</a></li>
      <li><a href="{% url 'accounts:register' %}">Register</a></li>
    {% endif %}
  </ul>
  

backstore/accounts/templates/login.html
{% block content %}
<h2>Login</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form>
<p>Not a member? <a href="{% url 'accounts:register' %}">Register</a></p>

{% endblock %}

backstore/accounts/templates/profile copy.html
{% block content %}
  <h2>Profile</h2>
  <p>Username: {{ user.username }}</p>
  <p>Email: {{ user.email }}</p>
  <a href="{% url 'accounts:logout' %}">Logout</a>
{% endblock %}

backstore/accounts/templates/profile.html
{% block title %}Profile{% endblock %}

{% block content %}
  <h2>Profile</h2>
  <h3>Account Information</h3>
  <form method="post" action="{% url 'accounts:update_profile' %}">
    {% csrf_token %}
    <div class="form-group">
      <label for="username">Username:</label>
      <input type="text" class="form-control" id="username" value="{{ user.username }}" disabled>
    </div>
    <div class="form-group">
      <label for="first_name">First Name:</label>
      <input type="text" class="form-control" id="first_name" name="first_name" value="{{ user.first_name }}">
    </div>
    <div class="form-group">
      <label for="last_name">Last Name:</label>
      <input type="text" class="form-control" id="last_name" name="last_name" value="{{ user.last_name }}">
    </div>
    <div class="form-group">
      <label for="email">Email:</label>
      <input type="email" class="form-control" id="email" name="email" value="{{ user.email }}">
    </div>
    <h3>Change Password</h3>
    <div class="form-group">
      <label for="old_password">Old Password:</label>
      <input type="password" class="form-control" id="old_password" name="old_password">
    </div>
    <div class="form-group">
      <label for="new_password1">New Password:</label>
      <input type="password" class="form-control" id="new_password1" name="new_password1">
    </div>
    <div class="form-group">
      <label for="new_password2">Confirm New Password:</label>
      <input type="password" class="form-control" id="new_password2" name="new_password2">
    </div>
    <button type="submit" class="btn btn-primary">Save Changes</button>
  </form>


  <a href="{% url 'accounts:logout' %}">Logout</a>
{% endblock %}

backstore/accounts/templates/register copy.html
{% block content %}
<h2>Register</h2>
{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li class="{{ message.tags }}">{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Register</button>
</form>
<p>Already a member? <a href="{% url 'accounts:login' %}">Login</a></p>
{% endblock %}

backstore/accounts/templates/register.html
{% block content %}
  <h2>Register!</h2>
  
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_username">Username:</label>
      <input type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required="" id="id_username">
    </div>
    <div class="form-group">
      <label for="id_email">Email:</label>
      <input type="email" name="email" maxlength="254" required="" id="id_email">
    </div>
    <div class="form-group">
      <label for="id_password1">Password:</label>
      <input type="password" name="password1" autocomplete="new-password" required="" id="id_password1">
    </div>
    <div class="form-group">
      <label for="id_password2">Password confirmation:</label>
      <input type="password" name="password2" autocomplete="new-password" required="" id="id_password2">
    </div>
    <button type="submit" class="btn btn-primary">Register</button>
  </form>
  <p>Already a member? <a href="{% url 'accounts:login' %}">Login</a></p>
{% endblock %}

backstore/accounts/templates/update_profile.html
{% block content %}
  <h2>Update Profile</h2>
  <form method="post" action="{% url 'accounts:update_profile' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button type="submit">Update</button>
  </form>
{% endblock %}

backstore/accounts/templates/view_profile.html
{% block content %}
    <h2>{{ user.username }}</h2>
    <p>Email: {{ user.email }}</p>
    <p>Phone Number: {{ user.account.phone_number }}</p>
    <p>Address: {{ user.account.address }}</p>
    <a href="{% url 'accounts:update_profile' %}">Update Profile</a>
    <a href="{% url 'accounts:logout' %}">Logout</a>
{% endblock %}